package launch

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"syscall"
	"time"

	"golang.org/x/sys/windows"
)

const (
	StartCommand         = "start"
	InternalRunTrayArg   = "--run-tray"
	startupStatusFileArg = "--startup-status-file"
	startupTimeout       = 10 * time.Second
	statusStarted        = "started"
	statusAlreadyRunning = "already_running"
	statusFailedPrefix   = "failed:"
	startupPollInterval  = 100 * time.Millisecond
)

// ParseInternalStartupStatusPath returns the status file path for an
// internally spawned tray process.
func ParseInternalStartupStatusPath(args []string) (string, bool) {
	if len(args) == 0 || args[0] != InternalRunTrayArg {
		return "", false
	}

	for i := 1; i < len(args); i++ {
		if args[i] == startupStatusFileArg && i+1 < len(args) {
			return args[i+1], true
		}
		if after, ok := strings.CutPrefix(args[i], startupStatusFileArg+"="); ok {
			return after, true
		}
	}

	return "", true
}

// IsStartCommand reports whether the args request explicit detached startup.
func IsStartCommand(args []string) bool {
	return len(args) > 0 && args[0] == StartCommand
}

// StartDetached launches a tray instance in the background and waits for a
// startup result.
func StartDetached() error {
	exePath, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolve executable path: %w", err)
	}

	statusFile, err := os.CreateTemp("", "kbdlock-startup-*.status")
	if err != nil {
		return fmt.Errorf("create startup status file: %w", err)
	}
	statusPath := statusFile.Name()
	if err := statusFile.Close(); err != nil {
		return fmt.Errorf("close startup status file: %w", err)
	}
	defer func() {
		_ = os.Remove(statusPath)
	}()

	//nolint:gosec // exePath is the current executable path returned by os.Executable.
	cmd := exec.Command(exePath, InternalRunTrayArg, startupStatusFileArg, statusPath)
	cmd.SysProcAttr = &syscall.SysProcAttr{
		CreationFlags: windows.DETACHED_PROCESS | windows.CREATE_NEW_PROCESS_GROUP,
		HideWindow:    true,
	}

	if err := cmd.Start(); err != nil {
		return fmt.Errorf("start background process: %w", err)
	}
	if cmd.Process != nil {
		_ = cmd.Process.Release()
	}

	deadline := time.Now().Add(startupTimeout)
	for time.Now().Before(deadline) {
		status, err := readStartupStatus(statusPath)
		if err == nil && status != "" {
			switch {
			case status == statusStarted, status == statusAlreadyRunning:
				return nil
			case strings.HasPrefix(status, statusFailedPrefix):
				return errors.New(strings.TrimSpace(strings.TrimPrefix(status, statusFailedPrefix)))
			default:
				return fmt.Errorf("unexpected startup status: %s", status)
			}
		}

		time.Sleep(startupPollInterval)
	}

	return fmt.Errorf("timed out waiting for background startup")
}

// Reporter sends one-shot startup status messages back to a launching parent.
type Reporter struct {
	statusPath string
}

// NewReporter creates a startup reporter for an optional status path.
func NewReporter(statusPath string) *Reporter {
	return &Reporter{statusPath: statusPath}
}

// ReportStarted reports successful tray startup.
func (r *Reporter) ReportStarted() {
	r.report(statusStarted)
}

// ReportAlreadyRunning reports an already-running tray instance.
func (r *Reporter) ReportAlreadyRunning() {
	r.report(statusAlreadyRunning)
}

// ReportFailed reports startup failure.
func (r *Reporter) ReportFailed(message string) {
	r.report(statusFailedPrefix + " " + strings.TrimSpace(message))
}

func (r *Reporter) report(status string) {
	if r == nil || r.statusPath == "" {
		return
	}

	_ = os.WriteFile(r.statusPath, []byte(status+"\n"), 0o600)
}

func readStartupStatus(path string) (string, error) {
	//nolint:gosec // path is generated by StartDetached or passed via the hidden internal startup arg.
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(data)), nil
}
